### ISSUE TITLE
Builder doesn't add tags to notes

### ISSUE THREAD

**Issue by axelboc** [OnkelTem/anki-dm#3]
I can see the tags for each note in `data.csv`,  but the builder seems to miss them. The `tags` arrays are all empty in the JSON output.

**Comment by OnkelTem** [comment]
Oops, a typo in code.

Should be fixed by this:
https://github.com/OnkelTem/anki-dm/commit/7ed1e4cd68a9f68c2cac5c25db15c1d6abf9a4ae

Thanks Axel!
