### ISSUE TITLE
Translated deck name

### ISSUE THREAD

**Issue by axelboc** [OnkelTem/anki-dm#5]
I've just finished putting the German translations into the data file of the _Ultimate Geography_ deck. So easy!! Just a couple of questions regarding the build. (I'll create two separate issues.)

The German deck gets named `Ultimate Geography[de]`. Would it be possible to change the format to `Ultimate Geography [DE]` or `Ultimate Geography (DE)` ?

In the future, it may be worth making this configurable, perhaps through an option in the decks' `build.json` with a value of the sort: `"$name ($CODE)"`. Not worth it for now, though.

**Comment by OnkelTem** [comment]
Sorry for the delay Axel.

> The German deck gets named Ultimate Geography[de]. Would it be possible to change the format to Ultimate Geography [DE] or Ultimate Geography (DE) ?

Yeah, sure. I picked just the first name which had come to my mind. So we should think about how to make it configurable.

> In the future, it may be worth making this configurable, perhaps through an option in the decks' build.json with a value of the sort: "$name ($CODE)". Not worth it for now, though.

Sure, that's possible. But shouldn't it be a global option instead? We could add it as a parameter to the "extra" section of `composer.json`.

**Comment by axelboc** [comment]
Sounds good! Just thought a sub-deck may want to use a different pattern but that doesn't really make sense... 😆
