### ISSUE TITLE
Translated deck description

### ISSUE THREAD

**Issue by axelboc** [OnkelTem/anki-dm#6]
I don't believe it is yet possible to translate the description of a deck. The most straightforward solution I can think of would be to allow for localised versions of `desc.html` (including in deck folders):

```
src/
├── decks/
│   ├── Ultimate Geography/
│   │      ├── desc.html
│   │      └── desc.de.html
├── desc.html
└── desc.de.html
```

What do you think?

**Comment by OnkelTem** [comment]
You're right, it's not yet possible. You proposition seems reasonable to me. Let's do it.
